server:
    port: 8080
    servlet:
        context-path: /APIHotmart
        
        
spring:
    datasource:
            driver-class-name: org.postgresql.Driver
            url: postgres://gvpbmbiibcluty:f9a3a4afb34c552b2a4a1dc5f38cd4187dac8e616ff60fca191705b8ecdb5e27@ec2-54-236-137-173.compute-1.amazonaws.com:5432/d6e70rp307nae5
            username: gvpbmbiibcluty
            password: f9a3a4afb34c552b2a4a1dc5f38cd4187dac8e616ff60fca191705b8ecdb5e27
            
jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
    ddl-auto: nome

application:
    description: Projeto Cristiano Silva
