server:
    port: 8080
    servlet:
        context-path: /APIHotmart
        
        
spring:
    datasource:
            driver-class-name: org.postgresql.Driver
            url: jdbc:postgresql://192.168.15.21:5432/postgres
            username: postgres
            password: 123456
            
jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
    ddl-auto: nome

application:
    description: Projeto Cristiano Silva teste de API
